In [1]:
import torch

In [3]:
x = torch.randn(4, 5)
y = torch.randn(4, 5)
z = torch.randn(4, 5)

print(x)
print(y)
print(z)

tensor([[-0.7975,  1.2527, -1.5467, -2.2602, -0.2776],
        [ 1.7801, -1.1552,  1.0755,  0.1323, -0.7811],
        [ 0.6369, -0.0753, -0.0263, -0.0788,  1.5758],
        [-0.1304,  0.0180, -0.2096,  0.4282,  0.0706]])
tensor([[-0.3462,  1.1084,  0.1829,  1.1984, -0.0422],
        [ 1.5083,  0.7871,  2.1530,  0.2748, -0.3317],
        [-0.2050, -0.4623,  0.1864, -0.1468, -1.5075],
        [ 0.8196, -0.9028, -0.0060,  0.1228, -0.6705]])
tensor([[-0.9807, -0.6556, -1.0258,  0.7146, -2.3347],
        [-1.1497,  0.5412, -1.1605, -0.6627, -0.2414],
        [-0.0277, -0.5762,  0.1039,  0.6253,  0.5439],
        [ 1.9239,  0.9743,  0.2935, -1.4634, -0.0098]])


In [4]:
# max of the entire tensor
m = torch.max(x)
print(m)

tensor(1.7801)


# Max along a dimension 

torch.max(input, dim, keepdim=False, *, out=None)

In [6]:
m, idx = torch.max(x, 0)
print(x)
print(m)
print(idx)

tensor([[-0.7975,  1.2527, -1.5467, -2.2602, -0.2776],
        [ 1.7801, -1.1552,  1.0755,  0.1323, -0.7811],
        [ 0.6369, -0.0753, -0.0263, -0.0788,  1.5758],
        [-0.1304,  0.0180, -0.2096,  0.4282,  0.0706]])
tensor([1.7801, 1.2527, 1.0755, 0.4282, 1.5758])
tensor([1, 0, 1, 3, 2])


In [7]:
# 2 - 2
m, idx = torch.max(input=x, dim=0)
print(m)
print(idx)

tensor([1.7801, 1.2527, 1.0755, 0.4282, 1.5758])
tensor([1, 0, 1, 3, 2])


In [8]:
# 2 - 3
m, idx = torch.max(x, 0, False)
print(m)
print(idx)

tensor([1.7801, 1.2527, 1.0755, 0.4282, 1.5758])
tensor([1, 0, 1, 3, 2])


In [9]:
# 2 - 4
m, idx = torch.max(x, dim=0, keepdim=True)
print(m)
print(idx)

tensor([[1.7801, 1.2527, 1.0755, 0.4282, 1.5758]])
tensor([[1, 0, 1, 3, 2]])


In [10]:
# 2 - 5
p = (m, idx)
torch.max(x, 0, False, out=p)

print(p[0])
print(p[1])

tensor([1.7801, 1.2527, 1.0755, 0.4282, 1.5758])
tensor([1, 0, 1, 3, 2])


/tmp/ipykernel_2660/3302760378.py:3: UserWarning: An output with one or more elements was resized since it had shape [1, 5], which does not match the required output shape [5]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  ../aten/src/ATen/native/Resize.cpp:24.)
  torch.max(x, 0, False, out=p)


# Put onto different device

In [11]:
model = torch.nn.Linear(5, 1).to("cuda:0")

x = torch.randn(5).to("cuda:0")
y = model(x)

print(y.shape)


torch.Size([1])


# Match the dimension

In [12]:
x = torch.randn(4, 5)
y = torch.randn(5, 4)

y = y.transpose(0, 1)
z = z + y 

print(z.shape)

torch.Size([4, 5])


# Loss calculation

In [4]:
import torch.nn as nn 

L = nn.CrossEntropyLoss()
outs = torch.rand(5, 5)
labels = torch.Tensor([1, 2, 3, 4, 0])
print(labels)

labels = labels.long()
lossval = L(outs, labels)

print(outs)
print(labels)
print(lossval)

tensor([1., 2., 3., 4., 0.])
tensor([[0.1540, 0.9315, 0.3712, 0.2581, 0.7232],
        [0.0072, 0.9839, 0.8478, 0.6936, 0.3783],
        [0.3215, 0.4817, 0.2624, 0.2851, 0.7816],
        [0.5404, 0.9774, 0.8896, 0.6105, 0.7310],
        [0.7041, 0.0416, 0.5771, 0.3425, 0.0821]])
tensor([1, 2, 3, 4, 0])
tensor(1.4625)


# Data loader

When using the dataloader, we often like to shuffle the data. This is where torch.utils.data.DataLoader comes in handy. If each data is an index (0, 1, 2...) from the view of torch.utils.data.DataLoader, shuffling can simply can be done by shuffling an index array.

torch.utils.data.DataLoader will need two information to fulfill its role. First, it needs to know the length of the data. Second, once torch.utils.data.DataLoader outputs the index of the shuffling results, the datasets needs to return the corresponding data.

Therefore, torch.utils.data.Dataset provides the information by two functions. `__len__()` and `__getitem__()` to support torch.utils.data.Dataloader

In [5]:
dataset = "abcdefghijklmnopqrstuvwxyz"

In [6]:
for data in dataset:
    print(data)

a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z


In [7]:
import torch 
import torch.utils.data 

class ExampleDataset(torch.utils.data.Dataset):

    def __init__(self):
        self.data = "abcdefghijklmnopqrstuvwxyz"

    def __getitem__(self, idx): # if the index is idx, what will be data
        return self.data[idx]

    def __len__(self): # what is the length of the dataset
        return len(self.data)


dataset = ExampleDataset() # create the dataset
dataloader = torch.utils.data.DataLoader(
    dataset = dataset,
    shuffle = True, 
    batch_size = 1
)

for data in dataloader:
    print(data)

['t']
['k']
['r']
['q']
['d']
['m']
['x']
['j']
['a']
['u']
['f']
['y']
['o']
['s']
['h']
['c']
['g']
['w']
['e']
['z']
['p']
['b']
['v']
['n']
['i']
['l']


# Sample data augmentation 

A simple data augmentation technique can be done by changing the code in `__len()__` and `__getitem__()`. Suppose we want to double the length of the dataset by adding in the uppercase letters, using only the lowercase dataset, you can change the dataset to the following.